### ISSUE TITLE
[BUG] Footer overlapping on widgets

### ISSUE THREAD

**Issue by yashchaudhari008** [yashchaudhari008/minime#18]
![Image](https://github.com/yashchaudhari008/minime/assets/29065088/97a1dc59-2272-4d4f-b2d0-d741800330de)

Expected: Footer should not overlap

**Comment by Zume-z** [comment]
I made a pull request fixing this issue, https://github.com/yashchaudhari008/minime/pull/19. 
Let me know if you want me to update it at all.
