### ISSUE TITLE
[BUG] Fix footer on mobile devices

### ISSUE THREAD

**Issue by yashchaudhari008** [yashchaudhari008/minime#20]
Footer on mobile seems to be broken
### Todo:
- Center text when on mobile
- Calculate font-size for footer according to vw (for small screens only)

| Current | Expected |
| --- | --- |
| ![Image](https://github.com/yashchaudhari008/minime/assets/29065088/d7a6e47f-d528-495e-ba75-733b00f8a1a2) | ![Image](https://github.com/yashchaudhari008/minime/assets/29065088/be21c4ab-3ea1-4e8b-b8e5-7b079ff464a1) |

**Comment by mademoiselle-chantal** [comment]
Hello, @yashchaudhari008! I would like to work on this.

**Comment by yashchaudhari008** [comment]
Assigning to you @mademoiselle-chantal

**Comment by mademoiselle-chantal** [comment]
Thank you, @yashchaudhari008. I'm working on the issue.

**Comment by yashchaudhari008** [comment]
> Thank you, @yashchaudhari008. I'm working on the issue.

any updates @mademoiselle-chantal

**Comment by RahalBhupathi** [comment]
Hello @yashchaudhari008, I see this issue is still open. Can you please assign me? I am a new developer looking for first contributions and this looks like something I can do.
