### ISSUE TITLE
[FEATURE] Add setting page

### ISSUE THREAD

**Issue by yashchaudhari008** [yashchaudhari008/minime#28]
### Todos:

- Add Settings Icon
![Image](https://github.com/yashchaudhari008/minime/assets/29065088/e8d40ede-b143-40c0-b69d-8f65f1c2d29a)

- Settings Page should be on [/minime/settings](https://yashchaudhari008.github.io/minime/settings) URL

- Add Settings Page
![Image](https://github.com/yashchaudhari008/minime/assets/29065088/f39a1786-a300-4f56-a920-4ffeebece081)
> Make sure to structure the page such that the middle section can include multiple settings

**Comment by ARRY7686** [comment]
hey @yashchaudhari008 I am really interested in your project is ready to contribute to this issue
can you please assign it to me and mark it as hacktoberfest
thanks

**Comment by Sauhard74** [comment]
hey can i work on this issue?

**Comment by ARRY7686** [comment]
@yashchaudhari008 i almost finished working on this project, why did you un-assign me?

**Comment by ARRY7686** [comment]
@yashchaudhari008 
![Screenshot 2024-10-02 172713](https://github.com/user-attachments/assets/8160fb0e-db27-4371-8e6e-d5c25580d97a)

will this work?

**Comment by ARRY7686** [comment]
![image](https://github.com/user-attachments/assets/cff5087a-3612-4083-9b29-c848e315333b)
how about this?
@yashchaudhari008

**Comment by yashchaudhari008** [comment]
@ARRY7686 can you check designs attached on top, there is padding on left and right

**Comment by ARRY7686** [comment]
done @yashchaudhari008

**Comment by Chinmay9281** [comment]
@yashchaudhari008 I have created [PR](https://github.com/yashchaudhari008/minime/pull/52) for above issue.
