### ISSUE TITLE
Adding Contributing.md

### ISSUE THREAD

**Issue by preronagit** [yashchaudhari008/minime#45]
Want to add Contributing.md file to this repo.

**Comment by preronagit** [comment]
@yashchaudhari008 I would like to solve this issue. Please assign it to me.

**Comment by yashchaudhari008** [comment]
Hey @preronagit, contribution guidelines are already there in the README file. Are you suggesting to move it in a separate file?

**Comment by preronagit** [comment]
@yashchaudhari008 Yes, I think making a separate file containing contribution guidelines will be better.

**Comment by kartikey369-ind** [comment]
@yashchaudhari008 
If you could assign this issue to me, I would greatly appreciate it. I am eager to contribute and work on this enhancement for the project.

Steps I will take:

Research Best Practices: Look into common practices for contributing guidelines in open-source projects.
.Draft the Document: Create a draft of the CONTRIBUTING.md file that includes:
.Overview of the project
.Steps to contribute
.Code style guidelines
.Submission process
.How to report issues
.Contact information for questions
.Seek Feedback: Share the draft with the team for feedback and suggestions.
.Make Revisions: Incorporate any feedback received to improve the document.
.Finalize and Commit: Finalize the document and commit it to the repository.

**Comment by yashchaudhari008** [comment]
I don't think it is needed for now, hence closing this issue for now
