### ISSUE TITLE
[FEATURE] Bookmark should be opened on same page

### ISSUE THREAD

**Issue by yashchaudhari008** [yashchaudhari008/minime#5]
When the user clicks on the bookmark, a new tab opens. 

**New Change:** The bookmark should be opened on the same tab.

### Attachments: 

https://github.com/yashchaudhari008/minime/assets/29065088/dc02bfc2-5b82-4097-9b6d-88e2be3b36f3

**Comment by MRodriguez-M** [comment]
Hi, do you still need help with this? Could you please assign this to me so I can work on the feature?
