### ISSUE TITLE
[FEATURE] Add link to github repo

### ISSUE THREAD

**Issue by yashchaudhari008** [yashchaudhari008/minime#7]
### Todos: 
- Footer should be added as per designs
- When `Github Page` is clicked it should redirect to `https://github.com/yashchaudhari008/minime`
- When a user clicks on `yashchaudhari008`, it should take the user to `https://github.com/yashchaudhari008`
- When a user clicks on `contributors` , it should take the user to `https://github.com/yashchaudhari008/minime/graphs/contributors`

### Designs:

|![Image](https://github.com/yashchaudhari008/minime/assets/29065088/33fbd13f-cf78-4a6b-860b-7887ac951282)| ![Image](https://github.com/yashchaudhari008/minime/assets/29065088/8140d53c-7d5f-4d17-bf9b-cf2674e6843c)|
| --- | --- |

**Comment by HappyLife2** [comment]
Could you please mention the name of the file which should I work on or the link to the specific line in the code, Thanks.

**Comment by yashchaudhari008** [comment]
@HappyLife2 It seems @linyers already started working on it...

Feel free to explore other issues. Thanks

**Comment by linyers** [comment]
Hi, forgive me for not having requested earlier to be assigned to this issue. I just saw the revisions, and I will be working on it.

**Comment by HappyLife2** [comment]
@linyers, @yashchaudhari008 No problems, I thought I might work on it if no one does. Thank you for your support.

May I get feedback about how this problem will be solved to gain theoretical experience from it. Thanks
