### ISSUE TITLE
[FEATURE] Allow widgets to be rearranged

### ISSUE THREAD

**Issue by yashchaudhari008** [yashchaudhari008/minime#9]
As a user, I would like to have the option to rearrange the widgets according to my preference.

### Expected:
The user should be able to drag and drop, which will in turn re-arrange bookmarks accordingly. 
Something similar to https://glitch.com/~simple-drag-drop

https://github.com/yashchaudhari008/minime/assets/29065088/c0862560-2844-4bcd-8234-aa1a93460702

**Comment by HappyLife2** [comment]
Hi @yashchaudhari008 I have made changes to the code to build this feature, after the changes have been made the feature of rearranging is live now, should I commit the changes?

**Comment by yashchaudhari008** [comment]
Hey @HappyLife2 , great you are contributing. But make sure you get assigned before you start working on any ticket...

**Comment by HappyLife2** [comment]
Hey @yashchaudhari008 Thank you for bringing that to my attention. I was not aware of it, but I will certainly keep that in mind for the future. Your information is greatly appreciated. Kindly see if you can add this information also to the readme file for future contributors to be aware of this practice. If there's an existing guideline, kindly direct me to it, as I couldn't find it. Your insights are valued. Thank you!
